### ISSUE TITLE
Running from source problems

### ISSUE THREAD

**Issue by clach04** [exzhawk/disk_treemap#3]
Two issues that may be doc relate:

1. https://github.com/exzhawk/disk_treemap/blob/master/README.md?plain=1#L31 - fails for me with `git: 'submodules' is not a git command. See 'git --help'.`
2. https://github.com/exzhawk/disk_treemap/blob/master/README.md?plain=1#L33 - also failed for me with `error: [WinError 2] The system cannot find the file specified` - this appears to be due to not having "npm" in the path

Pip install worked fine! Thanks for making this available, I was literally about to start writing my own when I found this today :-)

**Comment by exzhawk** [comment]
1. There is a typo. The command should start with 'git submodule'. (without the 's' after 'submodule'). It will be fixed in a moment.
2. `npm` must be in `PATH` due to https://github.com/exzhawk/disk_treemap/blob/master/setup.py#L21. I don't know how to find the npm executable more smartly, so the build script just calls `npm` and relies on `PATH`. For Windows, install NodeJS from https://nodejs.org/en/download/. npm is bundled in the installer, and the installer adds npm into PATH by default. If the installer fails or you are on another platform, you can google that.
